import {
  UserProfile,
  Gym,
  Visit,
  FollowUp,
  ActivityTimelineItem,
  RepsiModule,
  Feature,
  Task,
  Bug,
  Blocker,
  DailyWorkLog,
  FeatureRequest,
  Release,
  NotificationItem,
} from "@/types";

export const SEED_USERS: UserProfile[] = [
  {
    id: "usr_admin_1",
    name: "Vikram Founder",
    email: "vikram@repsi.app",
    role: "ADMIN",
    department: "Executive",
    active_tasks_count: 3,
    completed_tasks_count: 24,
    open_bugs_count: 1,
    overdue_tasks_count: 0,
    created_at: "2026-01-15T09:00:00Z",
  },
  {
    id: "usr_sales_1",
    name: "Arun Sales (Salesperson A)",
    email: "arun.sales@repsi.app",
    role: "SALES",
    department: "Field Sales",
    phone: "+91 98450 11223",
    active_tasks_count: 6,
    completed_tasks_count: 42,
    open_bugs_count: 0,
    overdue_tasks_count: 1,
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "usr_sales_2",
    name: "Priya Sales (Salesperson B)",
    email: "priya.sales@repsi.app",
    role: "SALES",
    department: "Field Sales",
    phone: "+91 98450 22334",
    active_tasks_count: 4,
    completed_tasks_count: 38,
    open_bugs_count: 0,
    overdue_tasks_count: 0,
    created_at: "2026-02-10T10:00:00Z",
  },
  {
    id: "usr_pm_1",
    name: "Karthik PM",
    email: "karthik.pm@repsi.app",
    role: "PROJECT_MANAGER",
    department: "Product Management",
    active_tasks_count: 8,
    completed_tasks_count: 65,
    open_bugs_count: 3,
    overdue_tasks_count: 0,
    created_at: "2026-01-20T10:00:00Z",
  },
  {
    id: "usr_dev_1",
    name: "Dev Rohan",
    email: "rohan.dev@repsi.app",
    role: "DEVELOPER",
    department: "Engineering",
    active_tasks_count: 5,
    completed_tasks_count: 52,
    open_bugs_count: 4,
    overdue_tasks_count: 1,
    created_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "usr_qa_1",
    name: "Ananya QA",
    email: "ananya.qa@repsi.app",
    role: "QA",
    department: "Quality Assurance",
    active_tasks_count: 4,
    completed_tasks_count: 49,
    open_bugs_count: 6,
    overdue_tasks_count: 0,
    created_at: "2026-02-15T10:00:00Z",
  },
  {
    id: "usr_cs_1",
    name: "Deepa Success",
    email: "deepa.cs@repsi.app",
    role: "CUSTOMER_SUCCESS",
    department: "Customer Operations",
    active_tasks_count: 3,
    completed_tasks_count: 30,
    open_bugs_count: 1,
    overdue_tasks_count: 0,
    created_at: "2026-03-01T10:00:00Z",
  },
];

export const SEED_GYMS: Gym[] = [
  {
    id: "gym_1",
    name: "ABC Fitness",
    owner_name: "Arun Kumar",
    phone: "+91 98401 23456",
    whatsapp: "+91 98401 23456",
    email: "arun@abcfitness.in",
    website: "https://abcfitness.in",
    instagram: "@abcfitness_coimbatore",
    address: "42 Avinashi Road, Near Hope College",
    area: "Peelamedu",
    city: "Coimbatore",
    google_maps_url: "https://maps.google.com/?q=Peelamedu+Coimbatore",
    business_type: "Gym",
    members_count: 320,
    trainers_count: 8,
    branches_count: 1,
    current_software: "Excel Sheets",
    current_payment_system: "GPay QR / Cash",
    business_size: "Medium",
    stage: "DEMO_COMPLETED",
    expected_revenue: 36000,
    assigned_salesperson_id: "usr_sales_1",
    assigned_salesperson_name: "Arun Sales (Salesperson A)",
    created_at: "2026-09-20T10:00:00Z",
    updated_at: "2026-10-05T14:30:00Z",
  },
  {
    id: "gym_2",
    name: "FitZone Studio",
    owner_name: "Kavitha Ramesh",
    phone: "+91 97910 88776",
    whatsapp: "+91 97910 88776",
    email: "contact@fitzonestudio.com",
    address: "15 Race Course Road",
    area: "Race Course",
    city: "Coimbatore",
    business_type: "Fitness Studio",
    members_count: 180,
    trainers_count: 5,
    branches_count: 2,
    current_software: "Legacy Desktop Tool",
    current_payment_system: "Card Swiper",
    business_size: "Medium",
    stage: "TRIAL",
    expected_revenue: 54000,
    assigned_salesperson_id: "usr_sales_1",
    assigned_salesperson_name: "Arun Sales (Salesperson A)",
    created_at: "2026-09-22T11:00:00Z",
    updated_at: "2026-10-04T16:00:00Z",
  },
  {
    id: "gym_3",
    name: "PowerHouse Gym",
    owner_name: "Manoj Singh",
    phone: "+91 98840 55443",
    whatsapp: "+91 98840 55443",
    email: "manoj@powerhousegym.in",
    address: "108 100 Feet Road",
    area: "Gandhipuram",
    city: "Coimbatore",
    business_type: "CrossFit",
    members_count: 500,
    trainers_count: 12,
    branches_count: 3,
    current_software: "Paper Register",
    current_payment_system: "Cash / UPI",
    business_size: "Large",
    stage: "VISIT_PLANNED",
    expected_revenue: 84000,
    assigned_salesperson_id: "usr_sales_2",
    assigned_salesperson_name: "Priya Sales (Salesperson B)",
    created_at: "2026-09-28T09:30:00Z",
    updated_at: "2026-10-05T11:00:00Z",
  },
  {
    id: "gym_4",
    name: "Elite Fitness & Wellness",
    owner_name: "Dr. Suresh Babu",
    phone: "+91 94430 99112",
    whatsapp: "+91 94430 99112",
    email: "suresh@elitefitness.org",
    address: "77 RS Puram West",
    area: "RS Puram",
    city: "Coimbatore",
    business_type: "Wellness Center",
    members_count: 250,
    trainers_count: 6,
    branches_count: 1,
    current_software: "Generic CRM",
    current_payment_system: "Payment Gateway",
    business_size: "Medium",
    stage: "WON",
    expected_revenue: 48000,
    assigned_salesperson_id: "usr_sales_2",
    assigned_salesperson_name: "Priya Sales (Salesperson B)",
    created_at: "2026-09-10T12:00:00Z",
    updated_at: "2026-10-02T15:00:00Z",
  },
  {
    id: "gym_5",
    name: "IronForge Arena",
    owner_name: "Karthik Raja",
    phone: "+91 98422 33110",
    email: "karthik@ironforge.com",
    address: "21 Saravanampatti IT Corridor",
    area: "Saravanampatti",
    city: "Coimbatore",
    business_type: "Gym",
    members_count: 120,
    trainers_count: 3,
    branches_count: 1,
    current_software: "None",
    business_size: "Small",
    stage: "LOST",
    lost_reason: "Price too high",
    lost_notes: "Owner requested 50% discount which does not meet our minimum tier economics.",
    expected_revenue: 0,
    assigned_salesperson_id: "usr_sales_1",
    assigned_salesperson_name: "Arun Sales (Salesperson A)",
    created_at: "2026-09-15T08:00:00Z",
    updated_at: "2026-09-30T10:00:00Z",
  },
];

export const SEED_VISITS: Visit[] = [
  {
    id: "visit_1",
    gym_id: "gym_1",
    gym_name: "ABC Fitness",
    gym_area: "Peelamedu",
    owner_name: "Arun Kumar",
    salesperson_id: "usr_sales_1",
    salesperson_name: "Arun Sales (Salesperson A)",
    scheduled_at: "2026-10-05T10:00:00Z",
    time_slot: "10:00 AM",
    status: "COMPLETED",
    met_owner: true,
    person_met: "Arun Kumar",
    role_of_person_met: "Gym Owner & Head Coach",
    interested: true,
    demo_required: true,
    current_software: "Excel Sheets",
    main_pain_point: "Members entering without renewals and lack of automated WhatsApp reminders",
    budget: 35000,
    expected_decision_date: "2026-10-14",
    response_notes: "Owner was impressed with the QR attendance scanner speed and requested WhatsApp integration.",
    next_followup_date: "2026-10-08",
    next_action: "WhatsApp follow-up with pricing tier breakdown and demo video link",
    outcome: "High intent - Demo completed successfully",
    created_at: "2026-10-05T10:45:00Z",
    updated_at: "2026-10-05T10:45:00Z",
  },
  {
    id: "visit_2",
    gym_id: "gym_3",
    gym_name: "PowerHouse Gym",
    gym_area: "Gandhipuram",
    owner_name: "Manoj Singh",
    salesperson_id: "usr_sales_2",
    salesperson_name: "Priya Sales (Salesperson B)",
    scheduled_at: "2026-10-06T11:30:00Z",
    time_slot: "11:30 AM",
    status: "SCHEDULED",
    created_at: "2026-10-04T09:00:00Z",
    updated_at: "2026-10-04T09:00:00Z",
  },
  {
    id: "visit_3",
    gym_id: "gym_2",
    gym_name: "FitZone Studio",
    gym_area: "Race Course",
    owner_name: "Kavitha Ramesh",
    salesperson_id: "usr_sales_1",
    salesperson_name: "Arun Sales (Salesperson A)",
    scheduled_at: "2026-10-06T03:00:00Z",
    time_slot: "03:00 PM",
    status: "SCHEDULED",
    created_at: "2026-10-04T14:00:00Z",
    updated_at: "2026-10-04T14:00:00Z",
  },
];

export const SEED_FOLLOWUPS: FollowUp[] = [
  {
    id: "fup_1",
    gym_id: "gym_1",
    gym_name: "ABC Fitness",
    contact_name: "Arun Kumar",
    due_date: "2026-10-08",
    assigned_to_id: "usr_sales_1",
    assigned_to_name: "Arun Sales (Salesperson A)",
    type: "WHATSAPP",
    status: "PENDING",
    notes: "Follow-up regarding customized pricing proposal and WhatsApp reminder module timeline.",
    created_at: "2026-10-05T11:00:00Z",
  },
  {
    id: "fup_2",
    gym_id: "gym_2",
    gym_name: "FitZone Studio",
    contact_name: "Kavitha Ramesh",
    due_date: "2026-10-06",
    assigned_to_id: "usr_sales_1",
    assigned_to_name: "Arun Sales (Salesperson A)",
    type: "VISIT",
    status: "PENDING",
    notes: "In-person visit to onboard their 2nd branch managers onto trial instance.",
    created_at: "2026-10-04T15:00:00Z",
  },
];

export const SEED_ACTIVITIES: ActivityTimelineItem[] = [
  {
    id: "act_1",
    gym_id: "gym_1",
    user_id: "usr_sales_1",
    user_name: "Arun Sales",
    type: "VISIT",
    title: "Field Visit Completed",
    description: "Visited gym in Peelamedu, met owner Arun Kumar. Owner is highly interested in automated attendance.",
    created_at: "2026-10-05T10:45:00Z",
  },
  {
    id: "act_2",
    gym_id: "gym_1",
    user_id: "usr_sales_1",
    user_name: "Arun Sales",
    type: "DEMO",
    title: "Live Product Demo",
    description: "Demonstrated mobile QR check-in and automated expiry alerts on iPad.",
    created_at: "2026-10-05T11:15:00Z",
  },
  {
    id: "act_3",
    gym_id: "gym_1",
    user_id: "usr_sales_1",
    user_name: "Arun Sales",
    type: "FEATURE_REQUEST",
    title: "Feature Request Logged: FR-102",
    description: "Owner requested WhatsApp automated renewal reminder directly from REPSI notification service.",
    created_at: "2026-10-05T11:30:00Z",
  },
];

export const SEED_RELEASES: Release[] = [
  {
    id: "rel_1",
    version: "v1.5.0",
    name: "REPSI Autumn Operations & QR Scanner",
    release_date: "2026-10-15",
    status: "QA_VERIFICATION",
    description: "Major release containing Attendance improvements, Payment webhook upgrades, and Trainer management foundation.",
    modules_count: 4,
    features_count: 12,
    tasks_count: 18,
    bugs_count: 3,
    created_at: "2026-09-15T10:00:00Z",
  },
  {
    id: "rel_2",
    version: "v1.6.0",
    name: "REPSI WhatsApp Automation & Multi-Branch",
    release_date: "2026-11-05",
    status: "PLANNED",
    description: "Includes WhatsApp automatic renewals (FR-102), consolidated multi-branch reporting, and trainer commission matrix.",
    modules_count: 2,
    features_count: 6,
    tasks_count: 9,
    bugs_count: 0,
    created_at: "2026-10-01T10:00:00Z",
  },
];

export const SEED_MODULES: RepsiModule[] = [
  {
    id: "mod_1",
    name: "Attendance",
    code: "ATTENDANCE",
    description: "QR attendance scanning, biometric device sync, member check-in history, and peak gym hours heatmaps.",
    status: "DEVELOPMENT",
    owner_id: "usr_dev_1",
    owner_name: "Dev Rohan",
    priority: "P0",
    progress_percent: 70,
    start_date: "2026-09-01",
    deadline: "2026-10-12",
    release_id: "rel_1",
    release_name: "v1.5.0",
    features_count: 4,
    tasks_count: 6,
    bugs_count: 1,
    created_at: "2026-09-01T08:00:00Z",
    updated_at: "2026-10-05T12:00:00Z",
  },
  {
    id: "mod_2",
    name: "Membership",
    code: "MEMBERSHIP",
    description: "Tier plans, validity tracking, renewals, member profiles, pause membership rules, and automated invoice PDF generation.",
    status: "COMPLETED",
    owner_id: "usr_pm_1",
    owner_name: "Karthik PM",
    priority: "P1",
    progress_percent: 100,
    start_date: "2026-08-10",
    deadline: "2026-09-20",
    release_id: "rel_1",
    release_name: "v1.5.0",
    features_count: 5,
    tasks_count: 8,
    bugs_count: 0,
    created_at: "2026-08-10T08:00:00Z",
    updated_at: "2026-09-25T14:00:00Z",
  },
  {
    id: "mod_3",
    name: "Payments",
    code: "PAYMENTS",
    description: "UPI Autopay, Razorpay/Stripe webhooks, split-payment tracking, POS cash receipt ledger, and GST invoicing.",
    status: "QA",
    owner_id: "usr_dev_1",
    owner_name: "Dev Rohan",
    priority: "P0",
    progress_percent: 90,
    start_date: "2026-09-05",
    deadline: "2026-10-10",
    release_id: "rel_1",
    release_name: "v1.5.0",
    features_count: 4,
    tasks_count: 7,
    bugs_count: 1,
    created_at: "2026-09-05T08:00:00Z",
    updated_at: "2026-10-05T15:00:00Z",
  },
  {
    id: "mod_4",
    name: "Trainer",
    code: "TRAINER",
    description: "Personal training sessions scheduling, client progress logs, trainer commission calculation, and workout templates.",
    status: "DEVELOPMENT",
    owner_id: "usr_dev_1",
    owner_name: "Dev Rohan",
    priority: "P2",
    progress_percent: 50,
    start_date: "2026-09-15",
    deadline: "2026-10-25",
    release_id: "rel_1",
    release_name: "v1.5.0",
    features_count: 3,
    tasks_count: 5,
    bugs_count: 0,
    created_at: "2026-09-15T08:00:00Z",
    updated_at: "2026-10-04T11:00:00Z",
  },
  {
    id: "mod_5",
    name: "Reports",
    code: "REPORTS",
    description: "Revenue projection, churn analytics, trainer utilization, daily cash tally, and tax filing export.",
    status: "PLANNED",
    owner_id: "usr_pm_1",
    owner_name: "Karthik PM",
    priority: "P2",
    progress_percent: 25,
    start_date: "2026-10-01",
    deadline: "2026-10-30",
    release_id: "rel_2",
    release_name: "v1.6.0",
    features_count: 4,
    tasks_count: 4,
    bugs_count: 0,
    created_at: "2026-10-01T08:00:00Z",
    updated_at: "2026-10-05T09:00:00Z",
  },
  {
    id: "mod_6",
    name: "Notifications",
    code: "NOTIFICATIONS",
    description: "WhatsApp Cloud API integration, push notifications, renewal alerts, and broadcast marketing messages.",
    status: "DESIGN",
    owner_id: "usr_pm_1",
    owner_name: "Karthik PM",
    priority: "P1",
    progress_percent: 30,
    start_date: "2026-10-02",
    deadline: "2026-11-02",
    release_id: "rel_2",
    release_name: "v1.6.0",
    features_count: 3,
    tasks_count: 3,
    bugs_count: 0,
    created_at: "2026-10-02T08:00:00Z",
    updated_at: "2026-10-05T16:00:00Z",
  },
];

export const SEED_FEATURES: Feature[] = [
  {
    id: "feat_1",
    module_id: "mod_1",
    module_name: "Attendance",
    name: "QR Attendance",
    description: "Dynamic rotating QR code generation at front desk with instant mobile camera scan validation.",
    status: "IN_PROGRESS",
    priority: "P0",
    requested_by_count: 14,
    tasks_count: 2,
    created_at: "2026-09-02T08:00:00Z",
  },
  {
    id: "feat_2",
    module_id: "mod_1",
    module_name: "Attendance",
    name: "Manual Attendance",
    description: "Receptionist override search and manual check-in entry with audit log.",
    status: "DONE",
    priority: "P1",
    requested_by_count: 8,
    tasks_count: 1,
    created_at: "2026-09-03T08:00:00Z",
  },
  {
    id: "feat_3",
    module_id: "mod_1",
    module_name: "Attendance",
    name: "Attendance History",
    description: "Member calendar view showing streak, monthly count, and gym peak hours.",
    status: "IN_PROGRESS",
    priority: "P2",
    requested_by_count: 6,
    tasks_count: 1,
    created_at: "2026-09-04T08:00:00Z",
  },
  {
    id: "feat_4",
    module_id: "mod_1",
    module_name: "Attendance",
    name: "Attendance Reports",
    description: "Exportable CSV of monthly member attendance for trainers and management.",
    status: "BACKLOG",
    priority: "P2",
    requested_by_count: 4,
    tasks_count: 1,
    created_at: "2026-09-05T08:00:00Z",
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: "task_1",
    title: "Finish Attendance API",
    description: "Complete PostgreSQL batch insert endpoint and Redis/Appwrite realtime sync for gym front desk scanner.",
    module_id: "mod_1",
    module_name: "Attendance",
    feature_id: "feat_1",
    feature_name: "QR Attendance",
    assignee_id: "usr_dev_1",
    assignee_name: "Dev Rohan",
    reporter_id: "usr_pm_1",
    reporter_name: "Karthik PM",
    priority: "P0",
    status: "IN_PROGRESS",
    start_date: "2026-10-02",
    due_date: "2026-10-06",
    estimated_hours: 16,
    actual_hours: 12,
    dependencies: [],
    created_at: "2026-10-02T09:00:00Z",
    updated_at: "2026-10-05T14:00:00Z",
  },
  {
    id: "task_2",
    title: "Review Payment Module",
    description: "Audit Razorpay webhook idempotency and handle payment gateway timeout edge cases.",
    module_id: "mod_3",
    module_name: "Payments",
    assignee_id: "usr_dev_1",
    assignee_name: "Dev Rohan",
    reporter_id: "usr_pm_1",
    reporter_name: "Karthik PM",
    priority: "P1",
    status: "IN_REVIEW",
    start_date: "2026-10-03",
    due_date: "2026-10-07",
    estimated_hours: 8,
    actual_hours: 7,
    created_at: "2026-10-03T09:00:00Z",
    updated_at: "2026-10-05T11:00:00Z",
  },
  {
    id: "task_3",
    title: "Test Dashboard",
    description: "Verify role-based metrics accuracy and validate speed on low-bandwidth connections.",
    module_id: "mod_5",
    module_name: "Reports",
    assignee_id: "usr_qa_1",
    assignee_name: "Ananya QA",
    reporter_id: "usr_pm_1",
    reporter_name: "Karthik PM",
    priority: "P2",
    status: "TODO",
    start_date: "2026-10-05",
    due_date: "2026-10-08",
    estimated_hours: 10,
    actual_hours: 2,
    created_at: "2026-10-04T10:00:00Z",
    updated_at: "2026-10-05T09:00:00Z",
  },
  {
    id: "task_4",
    title: "Fix notification issue",
    description: "Resolve duplicate SMS triggers when members are renewed manually from backoffice.",
    module_id: "mod_6",
    module_name: "Notifications",
    assignee_id: "usr_dev_1",
    assignee_name: "Dev Rohan",
    reporter_id: "usr_cs_1",
    reporter_name: "Deepa Success",
    priority: "P1",
    status: "BLOCKED",
    blocker_reason: "Waiting for API credentials and sender ID approval from Meta/Telco provider.",
    start_date: "2026-09-28",
    due_date: "2026-10-03", // Overdue!
    estimated_hours: 6,
    actual_hours: 3,
    created_at: "2026-09-28T10:00:00Z",
    updated_at: "2026-10-04T16:00:00Z",
  },
  {
    id: "task_5",
    title: "Trainer module review",
    description: "Architecture review for trainer slot allocation and commission calculations.",
    module_id: "mod_4",
    module_name: "Trainer",
    assignee_id: "usr_pm_1",
    assignee_name: "Karthik PM",
    reporter_id: "usr_admin_1",
    reporter_name: "Vikram Founder",
    priority: "P2",
    status: "TODO",
    start_date: "2026-10-09",
    due_date: "2026-10-14",
    estimated_hours: 12,
    actual_hours: 0,
    created_at: "2026-10-05T09:00:00Z",
    updated_at: "2026-10-05T09:00:00Z",
  },
];

export const SEED_BUGS: Bug[] = [
  {
    id: "bug_1",
    bug_id: "BUG-1042",
    title: "Attendance count incorrect after member renewal",
    description: "When a member renews their monthly pass, their previous month's check-in counter is not resetting properly in the aggregate analytics view.",
    module_id: "mod_1",
    module_name: "Attendance",
    feature_id: "feat_1",
    feature_name: "QR Attendance",
    reporter_id: "usr_sales_1",
    reporter_name: "Arun Sales",
    assigned_to_id: "usr_dev_1",
    assigned_to_name: "Dev Rohan",
    qa_owner_id: "usr_qa_1",
    qa_owner_name: "Ananya QA",
    severity: "MAJOR",
    priority: "P1",
    environment: "Production",
    app_version: "v1.4.2",
    expected_result: "Check-in counter should compute month-to-date sessions using the current billing cycle start date.",
    actual_result: "Counter includes all-time sessions for the active year without isolating the current renewal interval.",
    steps_to_reproduce: "1. Open member Arun Kumar at ABC Fitness.\n2. Renew pass for October 2026.\n3. Check dashboard counter: shows 48 instead of 3.",
    status: "IN_PROGRESS",
    due_date: "2026-10-07",
    created_at: "2026-10-04T11:00:00Z",
    updated_at: "2026-10-05T10:00:00Z",
  },
  {
    id: "bug_2",
    bug_id: "BUG-1043",
    title: "Payment completely failing on mobile webhook",
    description: "Webhook callback handler throws 500 error when transaction payload contains special characters in customer notes.",
    module_id: "mod_3",
    module_name: "Payments",
    reporter_id: "usr_qa_1",
    reporter_name: "Ananya QA",
    assigned_to_id: "usr_dev_1",
    assigned_to_name: "Dev Rohan",
    qa_owner_id: "usr_qa_1",
    qa_owner_name: "Ananya QA",
    severity: "CRITICAL",
    priority: "P0",
    environment: "Staging",
    app_version: "v1.5.0-rc1",
    expected_result: "Webhook safely sanitizes JSON body and records successful payment event.",
    actual_result: "Uncaught JSON parse syntax error blocks order status update to PAID.",
    steps_to_reproduce: "1. Initiate payment with note 'CrossFit & Gym (Special)'.\n2. Trigger Razorpay test webhook.\n3. Server returns 500.",
    status: "ASSIGNED",
    due_date: "2026-10-06",
    created_at: "2026-10-05T08:30:00Z",
    updated_at: "2026-10-05T09:00:00Z",
  },
  {
    id: "bug_3",
    bug_id: "BUG-1044",
    title: "Dashboard loading slow on low-bandwidth 4G",
    description: "Initial page bundle loads unnecessary heavy charting chunks before first contentful paint.",
    module_id: "mod_5",
    module_name: "Reports",
    reporter_id: "usr_sales_2",
    reporter_name: "Priya Sales",
    assigned_to_id: "usr_dev_1",
    assigned_to_name: "Dev Rohan",
    qa_owner_id: "usr_qa_1",
    qa_owner_name: "Ananya QA",
    severity: "MINOR",
    priority: "P2",
    environment: "Production",
    app_version: "v1.4.2",
    expected_result: "Dashboard shells load under 1.2s on simulated 4G connection.",
    actual_result: "Takes 4.1s due to unoptimized assets.",
    steps_to_reproduce: "Throttle Chrome DevTools to Fast 3G and navigate to /dashboard.",
    status: "QA_TESTING",
    due_date: "2026-10-10",
    created_at: "2026-10-03T14:00:00Z",
    updated_at: "2026-10-05T12:00:00Z",
  },
];

export const SEED_BLOCKERS: Blocker[] = [
  {
    id: "blk_1",
    task_id: "task_4",
    task_title: "Fix notification issue",
    person_id: "usr_dev_1",
    person_name: "Dev Rohan",
    blocker_reason: "Waiting for API credentials and sender ID approval from Meta/Telco provider.",
    blocked_since: "2026-10-01",
    dependency_desc: "Telco DLT Template Registration",
    owner_responsible_id: "usr_pm_1",
    owner_responsible_name: "Karthik PM",
    expected_resolution_date: "2026-10-08",
    status: "ACTIVE",
    created_at: "2026-10-01T10:00:00Z",
  },
];

export const SEED_DAILY_LOGS: DailyWorkLog[] = [
  {
    id: "log_1",
    user_id: "usr_dev_1",
    user_name: "Dev Rohan",
    date: "2026-10-05",
    completed_today: "- Fixed attendance API query optimization\n- Tested membership renewal edge cases",
    in_progress: "- Investigating BUG-1043 critical payment webhook error\n- Reviewing Trainer module database relationships",
    blocked: "- Waiting for API credentials for WhatsApp notification service",
    tomorrow_plan: "- Complete payment integration fixes\n- Ship v1.5.0-rc2 to QA staging",
    created_at: "2026-10-05T17:00:00Z",
  },
];

export const SEED_FEATURE_REQUESTS: FeatureRequest[] = [
  {
    id: "fr_1",
    request_code: "FR-102",
    gym_id: "gym_1",
    gym_name: "ABC Fitness",
    requested_by: "Arun Kumar (Owner)",
    title: "WhatsApp automatic renewal reminders",
    description: "Automated WhatsApp notifications sent to members 7 days, 3 days, and on expiration day with a 1-click UPI renewal link.",
    business_problem: "Gym receptionists spend 3+ hours daily manually messaging expired members. Over 25% of lapsed members cite forgetting their renewal date.",
    priority: "P1",
    customers_count: 5,
    status: "IN_PLANNING",
    product_decision: "Accepted into core roadmap. Assigned to Notifications Module for Release v1.6.0.",
    module_id: "mod_6",
    module_name: "Notifications",
    target_release_id: "rel_2",
    target_release_name: "v1.6.0",
    created_at: "2026-10-05T11:30:00Z",
    updated_at: "2026-10-05T14:00:00Z",
  },
  {
    id: "fr_2",
    request_code: "FR-103",
    gym_id: "gym_3",
    gym_name: "PowerHouse Gym",
    requested_by: "Manoj Singh",
    title: "Trainer Commission Matrix based on PT Renewals",
    description: "Calculate variable commission percentages based on trainer tier and client package size.",
    business_problem: "Manual spreadsheet calculation leads to payout disputes at month end.",
    priority: "P2",
    customers_count: 3,
    status: "PROPOSED",
    module_id: "mod_4",
    module_name: "Trainer",
    created_at: "2026-10-04T12:00:00Z",
    updated_at: "2026-10-04T12:00:00Z",
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif_1",
    user_id: "usr_sales_1",
    title: "Sales Follow-up Due",
    message: "Follow-up with ABC Fitness is due today regarding WhatsApp automation proposal.",
    type: "SALES",
    link: "/crm/gyms/gym_1",
    is_read: false,
    created_at: "2026-10-05T09:00:00Z",
  },
  {
    id: "notif_2",
    user_id: "usr_dev_1",
    title: "Critical Bug Assigned",
    message: "BUG-1043: Payment completely failing on mobile webhook assigned to you.",
    type: "DEV",
    link: "/bugs/bug_2",
    is_read: false,
    created_at: "2026-10-05T09:15:00Z",
  },
  {
    id: "notif_3",
    user_id: "usr_qa_1",
    title: "QA Verification Ready",
    message: "Payment module build v1.5.0-rc1 is ready for staging verification.",
    type: "QA",
    link: "/bugs/qa",
    is_read: false,
    created_at: "2026-10-05T10:00:00Z",
  },
  {
    id: "notif_4",
    user_id: "usr_admin_1",
    title: "Critical Attention Required",
    message: "1 critical blocker and 1 P0 bug need executive review before Friday release cutoff.",
    type: "FOUNDER",
    link: "/project/blockers",
    is_read: false,
    created_at: "2026-10-05T10:30:00Z",
  },
];
